# Generated by Django 2.2.5 on 2021-10-19 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='password',
            new_name='phone',
        ),
    ]
